# Общая длина строки для Ruff (и для lint E501, и для isort, и для formatter)
line-length = 120  # [web:12]

[lint]
select = [
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "F",    # Pyflakes
    "I",    # isort (импорты)
    "UP",   # pyupgrade
    "C4",   # flake8-comprehensions
]

ignore = [
    "E501",  # Длинные строки (пусть форматтер разрулит)
]

exclude = [
    ".git",
    "__pycache__",
    "venv",
    ".venv",
    "dist",
    "build",
]

[lint.isort]
