"""init tables

Revision ID: 68d8bc62a60f
Revises:
Create Date: 2026-01-15 13:08:06.384401
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "68d8bc62a60f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "package_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_package_types_name"), "package_types", ["name"], unique=True)
    op.create_table(
        "packages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("package_type_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("content_value_usd", sa.Float(), nullable=False),
        sa.Column("delivery_cost_rub", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["package_type_id"], ["package_types.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_packages_package_type_id"), "packages", ["package_type_id"], unique=False
    )
    op.create_index(op.f("ix_packages_session_id"), "packages", ["session_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_packages_session_id"), table_name="packages")
    op.drop_index(op.f("ix_packages_package_type_id"), table_name="packages")
    op.drop_table("packages")
    op.drop_index(op.f("ix_package_types_name"), table_name="package_types")
    op.drop_table("package_types")
    # ### end Alembic commands ###
