"""content_value_usd decimal

Revision ID: ffb37ab0040c
Revises: 6dffd3528064
Create Date: 2026-01-29 06:48:40.315221

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "ffb37ab0040c"
down_revision: Union[str, Sequence[str], None] = "6dffd3528064"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "packages",
        "content_value_usd",
        existing_type=mysql.FLOAT(),
        type_=sa.DECIMAL(precision=12, scale=2),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "packages",
        "content_value_usd",
        existing_type=sa.DECIMAL(precision=12, scale=2),
        type_=mysql.FLOAT(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
