name: CI

on:
  push:
    branches: [main, dev]  # добавить dev
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - uses: snok/install-poetry@v1
      with:
        virtualenvs-create: false
    - name: Install dependencies
      run: poetry install --no-root
    - name: Lint with Ruff
      run: poetry run ruff check . --fix
    - name: Format with Ruff
      run: poetry run ruff format .
    - name: Run tests
      run: |
        docker compose up -d --build
        sleep 15  # wait migrate/healthchecks
        poetry run pytest -q --cov --cov-report=term-missing
        docker compose down
